### PR TITLE
(hopefully) fix Masque support

### PR DESCRIPTION
**Pull request by Sanaka3**
taken from "normal" 2.0.8 version of weakauras2
upd: 2.0.8 weakauras2 doesn't exactly work (if at all) with Masque - this here only prevents it from completely breaking after making/importing icons. needs to be looked into more thoroughly

### CODE REVIEW

**Comment by Sanaka3** [comment]
upd: 2.0.8 weakauras2 doesn't exactly work (if at all) with Masque - this here only prevents it from completely breaking after making/importing icons. needs to be looked into more thoroughly

**Comment by Maczuga** [comment]
I am 99% sure that there is no need to rename any ```region.MSQGroup``` occurrences to ```region.LBFGroup```.

Also, have you tested it?
https://github.com/Maczuga/WeakAuras2-MoP/pull/13/commits/03e6ddeb9d6b8c09eecbf5084785277a5d173c85#diff-af09a7a12bdcb60fd498755c24ca9e4a99cd0d08a7e49d0aaaea599d2cc56524R5

LBF is always nil, you never initialize LibButtonFacade

**Comment by Sanaka3** [comment]
Yes, tested it. It "worked" as 2.0.8 version did (as in, didn't fire up any errors). Otherwise, Masque doesn't affect it at all As updated before, it seems to break. Pasting error in case it helps to root out the cause of it. Happens on addon load:
```
Message: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:8: attempt to call method 'AddType' (a nil value)
Time: 02/26/21 13:06:05
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:8: in main chunk

Locals: AddonName = "WeakAuras"
Private = <table> {
 HandleGlowAction = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3060
 frame_strata_types = <table> {
 }
 combat_event_type = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2231
 UIDtoID = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1657
 IsEnvironmentInitialized = <function> defined @Interface\AddOns\WeakAuras\AuraEnvironment.lua:174
 form_types = <table> {
 }
 CleanArchive = <function> defined @Interface\AddOns\WeakAuras\History.lua:21
 RunConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:644
 tooltip_count = <table> {
 }
 pet_spec_types = <table> {
 }
 ReplaceLocalizedRaidMarkers = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:5033
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 FinishLoadUnload = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1641
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:152
 array_entry_name_types = <table> {
 }
 RegisterLoadEvents = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1509
 FixGroupChildrenOrderForGroup = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3518
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 CheckSpellCooldown = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2102
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1866
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2288
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3196
 NeedToRepairDatabase = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2064
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:55
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2162
 IsOptionsProcessingPaused = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1278
 ValueFromPath = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3470
 Login = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:941
 GetTriggerConditions = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3306
 trigger_require_types_one = <table> {
 }
 bufftrigger_progress_behavior_types = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <table> {
 }
 pvp_talent_types_specific = <table> {
 }
 item_weapon_types = <table> {
 }
 grow_types = <table> {
 }
 GetRegionByUID = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2843
 combatlog_raid_mark_check_type = <table> {
 }
 trigger_modes = <table> {
 }
 category_event_prototype = <table> {
 }
 dynamic_texts = <table> {
 }
 character_types = <table> {
 }
 orientation_types = <table> {
 }
 difficulty_info = <table> {
 }
 CheckSpellKnown = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2090
 aura_types = <table> {
 }
 icon_side_types = <table> {
 }
 al
```

**Comment by Maczuga** [comment]
Well. That just hides the error, masque won't work after all with WA. I have a proper commit coming with support for 548 Masque.

**Pull request closed without merging**
